#!/bin/bash

# Copy to .git/hooks in the project root
# E.g. cp pre-push ../.git/hooks/ && chmod +x ../.git/hooks/pre-push

echo "Running ktlint..."
sh scripts/ktlint.sh

RESULT=$?
if [ $RESULT -ne 0 ]; then
 echo "Ktlint error. Run sh ./ktlint.sh -F to apply fixes"
 exit 1
fi
